#!/bin/bash
# สคริปต์แก้ไขปัญหา Evaluator ไม่เห็นงาน

echo "====================================="
echo "แก้ไขปัญหา: Evaluator ไม่เห็นงาน"
echo "====================================="
echo ""
echo "วิธีรัน SQL:"
echo "1. ใช้ Docker:"
echo "   docker exec -i pes-db-1 mysql -uroot -proot_password pes < quick-fix-periods.sql"
echo ""
echo "2. หรือใช้ MySQL client:"
echo "   mysql -h localhost -P 3306 -u root -p pes < quick-fix-periods.sql"
echo ""
echo "3. หรือ copy SQL จากไฟล์ quick-fix-periods.sql ไป run ใน workbench/phpmyadmin"
echo ""
echo "====================================="
echo "📋 หลังรัน SQL แล้ว:"
echo "====================================="
echo "1. Restart frontend: cd frontend && npm run dev"
echo "2. เปิดเบราว์เซอร์และ login ด้วย evaluator1@ccollege.ac.th"
echo "3. ไปที่หน้า My Tasks"
echo "4. เปิด Browser Console (กด F12)"
echo "5. ดูว่า:"
echo "   - Console แสดง 'Total tasks count: 3' หรือมากกว่า"
echo "   - Dropdown แสดง periods ที่มีงาน (1, 4, 5)"
echo "   - เห็นรายการงาน 2-3 งาน"
echo "   - ไม่มี Vue warnings"
echo ""
